### ISSUE TITLE
sporadically erratic sorting of etching pathes on double sided boards

### ISSUE THREAD

**Issue by deHarro** [JohnAtl/pcbgcode#23]
Hi John,
this is not a real issue, since I cannot reproduce it... Or better, I can reproduce it, but only with a given, relatively complex, double sided design.
When I tried to reproduce the effect with a stripped down part of this very design, the effect doesn't appear.
So treat this only as a reminder to some strange happening from now and then.

I realized in the past and now again, that sometimes pcb-gcode behaves a little bit strange when etching the bottom side of double sided boards.
Normally the milling pathes (I will refer to the milling pathes as mtraces from now on) are sorted ascending from in to out, regarding the distance away from the signal trace. 
As far as I realized it, when the "issue" occurs, it happens on the bottom layer of double sided boards.
The "issue" is, the first mtrace is along the outer circumference of the trench. That is NOT normal.
The second mtrace is the "normally first" mtrace around the signal trace. 
The third mtrace is adjacent to the first mtrace.
The fourth mtrace is adjacent to the second mtrace.
...and so on, until the mtraces remove the last stripe of copper in the middle of the trench  between signal trace and remaining copper-clad.

I posted a [video of the above described action ](https://vimeo.com/manage/videos/746261234) on vimeo.

![grafik](https://user-images.githubusercontent.com/26298406/188307871-009fff44-d23a-4db6-92f7-d5e6a339e150.png)

The signal trace in the video is part of this design:

![grafik](https://user-images.githubusercontent.com/26298406/188307829-c11d7c46-f86a-491e-b53b-61cbdf3a872c.png)

I tried to reproduce the effect by stripping the design down to only consist of the two signal traces on the top and bottom layer, respectively:

![grafik](https://user-images.githubusercontent.com/26298406/188307933-62268b53-b56a-4111-bf02-eac50632281e.png)

But to no avail. This "design" is etched as expected.
....
On writing this I have an idea...
Ok, a short test later...
When I add a ground plane to the bottom side of the board, the mtraces are executed as described above.

![grafik](https://user-images.githubusercontent.com/26298406/188308265-f952cdc2-996b-4213-857e-bd52acecb6f0.png)

So I assume, the ground plane is treated as signal "trace" and so, as the outer rim of the isolating trench around the actual signal trace (the blue connection in the picture above) is nearer than the circumference of this blue signal trace, this outer rim is etched first.

All in all it's no bug, it's a feature and based on mathematics only :)
Having investigated and written on that , I leave it here for you to close...

Harald

**Comment by JohnAtl** [comment]
Thanks for reporting this, and following up with an investigation!
As you discovered, to pcbgcode, everything is a polygon, with no distinction between signals, ground planes, etc.
