### ISSUE TITLE
Does PCB-GCode Work with Latest Eagle Version on Mac?

### ISSUE THREAD

**Issue by TSJim** [JohnAtl/pcbgcode#4]
Wondering if PCB-Gcode works on Eagle 9.6 on Mac.  It seems to throw an error when I try to run it:

**/Applications/EAGLE-9.6.2/examples/ulps/examples/pcb-gcode.ulp(10):

Unable to open the include file 'source/pcb-gcode.h'**

Thank you!

**Comment by JohnAtl** [comment]
Yes, it does.
You'll want to get the .zip file from [here](https://github.com/JohnAtl/pcbgcode/releases/tag/Release-3.6.2.4).
When you unzip it, be sure that the directory structure is preserved.
Then you'll need to add the location of the pcb-gcode folder in your directory options. See docs/pcbgcode.pdf for details. The pdf is on your machine, or you can find it [here](https://github.com/JohnAtl/pcbgcode/blob/master/docs/pcbgcode.pdf).
